/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs/Observable";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { MetadataFileUAVDTO } from '../model/metadataFileUAVDTO';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class AcquisitionSessionsService {
    private basePath: string = 'https://localhost';

    constructor(@inject("IApiHttpClient") private httpClient: IHttpClient,
        @inject("IAPIConfiguration") private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }
    /**
     * Get the metadata for the acquisition session file
     * Retrieve the metadata for the acquisition session file. Need URL encoded of the vector type of the acquisition session (uav or drone)
     * @param vectorRdfType A vector rdf type URI
     * @param Authorization Access token given
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     
     */
    public get4PMetadataFile(vectorRdfType: string, Authorization: string, pageSize?: number, page?: number, observe?: 'body', headers?: Headers): Observable<Array<MetadataFileUAVDTO>>;
    public get4PMetadataFile(vectorRdfType: string, Authorization: string, pageSize?: number, page?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<MetadataFileUAVDTO>>>;
    public get4PMetadataFile(vectorRdfType: string, Authorization: string, pageSize?: number, page?: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!vectorRdfType){
            throw new Error('Required parameter vectorRdfType was null or undefined when calling get4PMetadataFile.');
        }

        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling get4PMetadataFile.');
        }

        let queryParameters: string[] = [];
        if (vectorRdfType !== undefined) {
            queryParameters.push("vectorRdfType="+encodeURIComponent(String(vectorRdfType)));
        }
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<MetadataFileUAVDTO>>> = this.httpClient.get(`${this.basePath}/acquisitionSessions/metadataFile?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<MetadataFileUAVDTO>>(httpResponse.response));
        }
        return response;
    }
}
