/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs/Observable";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { BrapiObservationDTO } from '../model/brapiObservationDTO';
import { BrapiObservationUnitDTO } from '../model/brapiObservationUnitDTO';
import { BrapiVariable } from '../model/brapiVariable';
import { StudyDTO } from '../model/studyDTO';
import { StudyDetails } from '../model/studyDetails';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class Brapiv1studiesService {
    private basePath: string = 'https://localhost';

    constructor(@inject("IApiHttpClient") private httpClient: IHttpClient,
        @inject("IAPIConfiguration") private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }
    /**
     * List all the observation units measured in the study.
     * List all the observation units measured in the study.
     * @param studyDbId studyDbId
     * @param Authorization Access token given
     * @param observationLevel observationLevel
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     
     */
    public getObservationUnits(studyDbId: string, Authorization: string, observationLevel?: string, pageSize?: number, page?: number, observe?: 'body', headers?: Headers): Observable<Array<BrapiObservationUnitDTO>>;
    public getObservationUnits(studyDbId: string, Authorization: string, observationLevel?: string, pageSize?: number, page?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<BrapiObservationUnitDTO>>>;
    public getObservationUnits(studyDbId: string, Authorization: string, observationLevel?: string, pageSize?: number, page?: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!studyDbId){
            throw new Error('Required parameter studyDbId was null or undefined when calling getObservationUnits.');
        }

        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getObservationUnits.');
        }

        let queryParameters: string[] = [];
        if (observationLevel !== undefined) {
            queryParameters.push("observationLevel="+encodeURIComponent(String(observationLevel)));
        }
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<BrapiObservationUnitDTO>>> = this.httpClient.get(`${this.basePath}/brapi/v1/studies/${encodeURIComponent(String(studyDbId))}/observationunits?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<BrapiObservationUnitDTO>>(httpResponse.response));
        }
        return response;
    }
    /**
     * List all the observation variables measured in the study.
     * List all the observation variables measured in the study.
     * @param studyDbId studyDbId
     * @param Authorization Access token given
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     
     */
    public getObservationVariables(studyDbId: string, Authorization: string, pageSize?: number, page?: number, observe?: 'body', headers?: Headers): Observable<Array<BrapiVariable>>;
    public getObservationVariables(studyDbId: string, Authorization: string, pageSize?: number, page?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<BrapiVariable>>>;
    public getObservationVariables(studyDbId: string, Authorization: string, pageSize?: number, page?: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!studyDbId){
            throw new Error('Required parameter studyDbId was null or undefined when calling getObservationVariables.');
        }

        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getObservationVariables.');
        }

        let queryParameters: string[] = [];
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<BrapiVariable>>> = this.httpClient.get(`${this.basePath}/brapi/v1/studies/${encodeURIComponent(String(studyDbId))}/observationvariables?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<BrapiVariable>>(httpResponse.response));
        }
        return response;
    }
    /**
     * Get the observations associated to a specific study
     * Get the observations associated to a specific study
     * @param studyDbId studyDbId
     * @param Authorization Access token given
     * @param observationVariableDbIds observationVariableDbIds
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     
     */
    public getObservations(studyDbId: string, Authorization: string, observationVariableDbIds?: Array<string>, pageSize?: number, page?: number, observe?: 'body', headers?: Headers): Observable<Array<BrapiObservationDTO>>;
    public getObservations(studyDbId: string, Authorization: string, observationVariableDbIds?: Array<string>, pageSize?: number, page?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<BrapiObservationDTO>>>;
    public getObservations(studyDbId: string, Authorization: string, observationVariableDbIds?: Array<string>, pageSize?: number, page?: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!studyDbId){
            throw new Error('Required parameter studyDbId was null or undefined when calling getObservations.');
        }

        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getObservations.');
        }

        let queryParameters: string[] = [];
        if (observationVariableDbIds) {
            observationVariableDbIds.forEach((element) => {
                queryParameters.push("observationVariableDbIds="+encodeURIComponent(String(observationVariableDbIds)));
            })
        }
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<BrapiObservationDTO>>> = this.httpClient.get(`${this.basePath}/brapi/v1/studies/${encodeURIComponent(String(studyDbId))}/observations?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<BrapiObservationDTO>>(httpResponse.response));
        }
        return response;
    }
    /**
     * Retrieve studies information
     * Retrieve studies information
     * @param Authorization Access token given
     * @param studyDbId Search by studyDbId
     * @param commonCropName Search by commonCropName
     * @param seasonDbId Search by seasonDbId
     * @param active Filter active status true/false
     * @param sortBy Name of the field to sort by: studyDbId, commonCropName or seasonDbId
     * @param sortOrder Sort order direction - ASC or DESC
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     
     */
    public getStudies(Authorization: string, studyDbId?: string, commonCropName?: string, seasonDbId?: string, active?: string, sortBy?: string, sortOrder?: string, pageSize?: number, page?: number, observe?: 'body', headers?: Headers): Observable<Array<StudyDTO>>;
    public getStudies(Authorization: string, studyDbId?: string, commonCropName?: string, seasonDbId?: string, active?: string, sortBy?: string, sortOrder?: string, pageSize?: number, page?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<StudyDTO>>>;
    public getStudies(Authorization: string, studyDbId?: string, commonCropName?: string, seasonDbId?: string, active?: string, sortBy?: string, sortOrder?: string, pageSize?: number, page?: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getStudies.');
        }

        let queryParameters: string[] = [];
        if (studyDbId !== undefined) {
            queryParameters.push("studyDbId="+encodeURIComponent(String(studyDbId)));
        }
        if (commonCropName !== undefined) {
            queryParameters.push("commonCropName="+encodeURIComponent(String(commonCropName)));
        }
        if (seasonDbId !== undefined) {
            queryParameters.push("seasonDbId="+encodeURIComponent(String(seasonDbId)));
        }
        if (active !== undefined) {
            queryParameters.push("active="+encodeURIComponent(String(active)));
        }
        if (sortBy !== undefined) {
            queryParameters.push("sortBy="+encodeURIComponent(String(sortBy)));
        }
        if (sortOrder !== undefined) {
            queryParameters.push("sortOrder="+encodeURIComponent(String(sortOrder)));
        }
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<StudyDTO>>> = this.httpClient.get(`${this.basePath}/brapi/v1/studies?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<StudyDTO>>(httpResponse.response));
        }
        return response;
    }
    /**
     * Retrieve study details
     * Retrieve study details
     * @param studyDbId Search by studyDbId
     * @param Authorization Access token given
     
     */
    public getStudyDetails(studyDbId: string, Authorization: string, observe?: 'body', headers?: Headers): Observable<Array<StudyDetails>>;
    public getStudyDetails(studyDbId: string, Authorization: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<StudyDetails>>>;
    public getStudyDetails(studyDbId: string, Authorization: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!studyDbId){
            throw new Error('Required parameter studyDbId was null or undefined when calling getStudyDetails.');
        }

        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getStudyDetails.');
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<StudyDetails>>> = this.httpClient.get(`${this.basePath}/brapi/v1/studies/${encodeURIComponent(String(studyDbId))}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<StudyDetails>>(httpResponse.response));
        }
        return response;
    }
}
