/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs/Observable";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { BrapiTraitDTO } from '../model/brapiTraitDTO';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class Brapiv1traitsService {
    private basePath: string = 'https://localhost';

    constructor(@inject("IApiHttpClient") private httpClient: IHttpClient,
        @inject("IAPIConfiguration") private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }
    /**
     * Retrieve trait details by id
     * Retrieve trait details by id
     * @param traitDbId A trait URI (Unique Resource Identifier)
     * @param Authorization Access token given
     
     */
    public getTraitDetails1(traitDbId: string, Authorization: string, observe?: 'body', headers?: Headers): Observable<Array<BrapiTraitDTO>>;
    public getTraitDetails1(traitDbId: string, Authorization: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<BrapiTraitDTO>>>;
    public getTraitDetails1(traitDbId: string, Authorization: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!traitDbId){
            throw new Error('Required parameter traitDbId was null or undefined when calling getTraitDetails1.');
        }

        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getTraitDetails1.');
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<BrapiTraitDTO>>> = this.httpClient.get(`${this.basePath}/brapi/v1/traits/${encodeURIComponent(String(traitDbId))}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<BrapiTraitDTO>>(httpResponse.response));
        }
        return response;
    }
    /**
     * Retrieve the list of all traits available in the system
     * Retrieve the list of all traits available in the system
     * @param Authorization Access token given
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     
     */
    public getTraitsList(Authorization: string, pageSize?: number, page?: number, observe?: 'body', headers?: Headers): Observable<Array<BrapiTraitDTO>>;
    public getTraitsList(Authorization: string, pageSize?: number, page?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<BrapiTraitDTO>>>;
    public getTraitsList(Authorization: string, pageSize?: number, page?: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getTraitsList.');
        }

        let queryParameters: string[] = [];
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<BrapiTraitDTO>>> = this.httpClient.get(`${this.basePath}/brapi/v1/traits?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<BrapiTraitDTO>>(httpResponse.response));
        }
        return response;
    }
}
