/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs/Observable";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { Call } from '../model/call';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class Brapiv1callsService {
    private basePath: string = 'https://localhost';

    constructor(@inject("IApiHttpClient") private httpClient: IHttpClient,
        @inject("IAPIConfiguration") private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }
    /**
     * Check the available BrAPI calls
     * Check the available BrAPI calls
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     * @param dataType The data format supported by the call
     
     */
    public getCalls(pageSize?: number, page?: number, dataType?: string, observe?: 'body', headers?: Headers): Observable<Array<Call>>;
    public getCalls(pageSize?: number, page?: number, dataType?: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<Call>>>;
    public getCalls(pageSize?: number, page?: number, dataType?: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        let queryParameters: string[] = [];
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }
        if (dataType !== undefined) {
            queryParameters.push("dataType="+encodeURIComponent(String(dataType)));
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<Call>>> = this.httpClient.get(`${this.basePath}/brapi/v1/calls?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<Call>>(httpResponse.response));
        }
        return response;
    }
}
