/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs/Observable";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { BrapiVariable } from '../model/brapiVariable';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class Brapiv1variablesService {
    private basePath: string = 'https://localhost';

    constructor(@inject("IApiHttpClient") private httpClient: IHttpClient,
        @inject("IAPIConfiguration") private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }
    /**
     * List all the observation variables measured in the study.
     * List all the observation variables measured in the study.
     * @param studyDbId studyDbId
     * @param Authorization Access token given
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     
     */
    public getObservationVariables1(studyDbId: string, Authorization: string, pageSize?: number, page?: number, observe?: 'body', headers?: Headers): Observable<Array<BrapiVariable>>;
    public getObservationVariables1(studyDbId: string, Authorization: string, pageSize?: number, page?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<BrapiVariable>>>;
    public getObservationVariables1(studyDbId: string, Authorization: string, pageSize?: number, page?: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!studyDbId){
            throw new Error('Required parameter studyDbId was null or undefined when calling getObservationVariables1.');
        }

        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getObservationVariables1.');
        }

        let queryParameters: string[] = [];
        if (studyDbId !== undefined) {
            queryParameters.push("studyDbId="+encodeURIComponent(String(studyDbId)));
        }
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<BrapiVariable>>> = this.httpClient.get(`${this.basePath}/brapi/v1/observationvariables?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<BrapiVariable>>(httpResponse.response));
        }
        return response;
    }
    /**
     * Retrieve variable details by id
     * Retrieve variable details by id
     * @param observationVariableDbId A variable URI (Unique Resource Identifier)
     * @param Authorization Access token given
     
     */
    public getVariableDetails(observationVariableDbId: string, Authorization: string, observe?: 'body', headers?: Headers): Observable<Array<BrapiVariable>>;
    public getVariableDetails(observationVariableDbId: string, Authorization: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<BrapiVariable>>>;
    public getVariableDetails(observationVariableDbId: string, Authorization: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!observationVariableDbId){
            throw new Error('Required parameter observationVariableDbId was null or undefined when calling getVariableDetails.');
        }

        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getVariableDetails.');
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<BrapiVariable>>> = this.httpClient.get(`${this.basePath}/brapi/v1/variables/${encodeURIComponent(String(observationVariableDbId))}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<BrapiVariable>>(httpResponse.response));
        }
        return response;
    }
    /**
     * Retrieve the list of all variables available in the system
     * Retrieve the list of all variables available in the system
     * @param Authorization Access token given
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     
     */
    public getVariablesList(Authorization: string, pageSize?: number, page?: number, observe?: 'body', headers?: Headers): Observable<Array<BrapiVariable>>;
    public getVariablesList(Authorization: string, pageSize?: number, page?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<BrapiVariable>>>;
    public getVariablesList(Authorization: string, pageSize?: number, page?: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getVariablesList.');
        }

        let queryParameters: string[] = [];
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<BrapiVariable>>> = this.httpClient.get(`${this.basePath}/brapi/v1/variables?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<BrapiVariable>>(httpResponse.response));
        }
        return response;
    }
}
