/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs/Observable";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { EventGetDTO } from '../model/eventGetDTO';
import { EventPostDTO } from '../model/eventPostDTO';
import { EventPutDTO } from '../model/eventPutDTO';
import { RdfResourceDefinitionDTO } from '../model/rdfResourceDefinitionDTO';
import { ResponseFormPOST } from '../model/responseFormPOST';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class EventsService {
    private basePath: string = 'https://localhost';

    constructor(@inject("IApiHttpClient") private httpClient: IHttpClient,
        @inject("IAPIConfiguration") private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }
    /**
     * Get an event&#39;s annotations
     * Get an event&#39;s annotations
     * @param uri An event URI (Unique Resource Identifier)
     * @param Authorization Access token given
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     
     */
    public getEventAnnotations(uri: string, Authorization: string, pageSize?: number, page?: number, observe?: 'body', headers?: Headers): Observable<Array<RdfResourceDefinitionDTO>>;
    public getEventAnnotations(uri: string, Authorization: string, pageSize?: number, page?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<RdfResourceDefinitionDTO>>>;
    public getEventAnnotations(uri: string, Authorization: string, pageSize?: number, page?: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!uri){
            throw new Error('Required parameter uri was null or undefined when calling getEventAnnotations.');
        }

        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getEventAnnotations.');
        }

        let queryParameters: string[] = [];
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<RdfResourceDefinitionDTO>>> = this.httpClient.get(`${this.basePath}/events/${encodeURIComponent(String(uri))}/annotations?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<RdfResourceDefinitionDTO>>(httpResponse.response));
        }
        return response;
    }
    /**
     * Get the event corresponding to the search uri
     * Get the event corresponding to the search uri
     * @param uri An event URI (Unique Resource Identifier)
     * @param Authorization Access token given
     
     */
    public getEventByUri(uri: string, Authorization: string, observe?: 'body', headers?: Headers): Observable<Array<EventGetDTO>>;
    public getEventByUri(uri: string, Authorization: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<EventGetDTO>>>;
    public getEventByUri(uri: string, Authorization: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!uri){
            throw new Error('Required parameter uri was null or undefined when calling getEventByUri.');
        }

        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getEventByUri.');
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<EventGetDTO>>> = this.httpClient.get(`${this.basePath}/events/${encodeURIComponent(String(uri))}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<EventGetDTO>>(httpResponse.response));
        }
        return response;
    }
    /**
     * Get all events corresponding to the search parameters given.
     * Retrieve all events authorized for the user corresponding to the search parameters given
     * @param Authorization Access token given
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     * @param uri Search by uri
     * @param type Search by type
     * @param concernedItemUri Search by concerned item uri
     * @param concernedItemLabel Search by concerned item label
     * @param startDate Search by date - start of the range
     * @param endDate Search by date - end of the range
     
     */
    public getEvents(Authorization: string, pageSize?: number, page?: number, uri?: string, type?: string, concernedItemUri?: string, concernedItemLabel?: string, startDate?: string, endDate?: string, observe?: 'body', headers?: Headers): Observable<Array<EventGetDTO>>;
    public getEvents(Authorization: string, pageSize?: number, page?: number, uri?: string, type?: string, concernedItemUri?: string, concernedItemLabel?: string, startDate?: string, endDate?: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<EventGetDTO>>>;
    public getEvents(Authorization: string, pageSize?: number, page?: number, uri?: string, type?: string, concernedItemUri?: string, concernedItemLabel?: string, startDate?: string, endDate?: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getEvents.');
        }

        let queryParameters: string[] = [];
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }
        if (uri !== undefined) {
            queryParameters.push("uri="+encodeURIComponent(String(uri)));
        }
        if (type !== undefined) {
            queryParameters.push("type="+encodeURIComponent(String(type)));
        }
        if (concernedItemUri !== undefined) {
            queryParameters.push("concernedItemUri="+encodeURIComponent(String(concernedItemUri)));
        }
        if (concernedItemLabel !== undefined) {
            queryParameters.push("concernedItemLabel="+encodeURIComponent(String(concernedItemLabel)));
        }
        if (startDate !== undefined) {
            queryParameters.push("startDate="+encodeURIComponent(String(startDate)));
        }
        if (endDate !== undefined) {
            queryParameters.push("endDate="+encodeURIComponent(String(endDate)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<EventGetDTO>>> = this.httpClient.get(`${this.basePath}/events?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<EventGetDTO>>(httpResponse.response));
        }
        return response;
    }
    /**
     * POST event(s)
     * Register event(s)
     * @param Authorization Access token given
     * @param body JSON format of a list of events without URIs
     
     */
    public post2(Authorization: string, body?: Array<EventPostDTO>, observe?: 'body', headers?: Headers): Observable<ResponseFormPOST>;
    public post2(Authorization: string, body?: Array<EventPostDTO>, observe?: 'response', headers?: Headers): Observable<HttpResponse<ResponseFormPOST>>;
    public post2(Authorization: string, body?: Array<EventPostDTO>, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling post2.');
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';
        headers['Content-Type'] = 'application/json';

        const response: Observable<HttpResponse<ResponseFormPOST>> = this.httpClient.post(`${this.basePath}/events`, body , headers);
        if (observe == 'body') {
               return response.map(httpResponse => <ResponseFormPOST>(httpResponse.response));
        }
        return response;
    }
    /**
     * Update events
     * 
     * @param Authorization Access token given
     * @param body JSON format of a list of events with URIs
     
     */
    public put1(Authorization: string, body?: Array<EventPutDTO>, observe?: 'body', headers?: Headers): Observable<ResponseFormPOST>;
    public put1(Authorization: string, body?: Array<EventPutDTO>, observe?: 'response', headers?: Headers): Observable<HttpResponse<ResponseFormPOST>>;
    public put1(Authorization: string, body?: Array<EventPutDTO>, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling put1.');
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';
        headers['Content-Type'] = 'application/json';

        const response: Observable<HttpResponse<ResponseFormPOST>> = this.httpClient.put(`${this.basePath}/events`, body , headers);
        if (observe == 'body') {
               return response.map(httpResponse => <ResponseFormPOST>(httpResponse.response));
        }
        return response;
    }
}
