/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs/Observable";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { Infrastructure } from '../model/infrastructure';
import { RdfResourceDefinitionDTO } from '../model/rdfResourceDefinitionDTO';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class InfrastructuresService {
    private basePath: string = 'https://localhost';

    constructor(@inject("IApiHttpClient") private httpClient: IHttpClient,
        @inject("IAPIConfiguration") private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }
    /**
     * Get all infrastructure&#39;s details corresponding to the search uri
     * Retrieve all infrastructure&#39;s details authorized for the user corresponding to the searched uri
     * @param uri An infrastructure URI (Unique Resource Identifier)
     * @param Authorization Access token given
     * @param language Language
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     
     */
    public getInfrastructureDetails(uri: string, Authorization: string, language?: string, pageSize?: number, page?: number, observe?: 'body', headers?: Headers): Observable<Array<RdfResourceDefinitionDTO>>;
    public getInfrastructureDetails(uri: string, Authorization: string, language?: string, pageSize?: number, page?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<RdfResourceDefinitionDTO>>>;
    public getInfrastructureDetails(uri: string, Authorization: string, language?: string, pageSize?: number, page?: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!uri){
            throw new Error('Required parameter uri was null or undefined when calling getInfrastructureDetails.');
        }

        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getInfrastructureDetails.');
        }

        let queryParameters: string[] = [];
        if (language !== undefined) {
            queryParameters.push("language="+encodeURIComponent(String(language)));
        }
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<RdfResourceDefinitionDTO>>> = this.httpClient.get(`${this.basePath}/infrastructures/${encodeURIComponent(String(uri))}?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<RdfResourceDefinitionDTO>>(httpResponse.response));
        }
        return response;
    }
    /**
     * Get all infrastructures corresponding to the search params given
     * Retrieve all infrastructures authorized for the user corresponding to the searched params given
     * @param Authorization Access token given
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     * @param uri Search by uri
     * @param rdfType Search by type uri
     * @param label Search by label
     * @param language Language
     
     */
    public getInfrastructuresBySearch(Authorization: string, pageSize?: number, page?: number, uri?: string, rdfType?: string, label?: string, language?: string, observe?: 'body', headers?: Headers): Observable<Array<Infrastructure>>;
    public getInfrastructuresBySearch(Authorization: string, pageSize?: number, page?: number, uri?: string, rdfType?: string, label?: string, language?: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<Infrastructure>>>;
    public getInfrastructuresBySearch(Authorization: string, pageSize?: number, page?: number, uri?: string, rdfType?: string, label?: string, language?: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getInfrastructuresBySearch.');
        }

        let queryParameters: string[] = [];
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }
        if (uri !== undefined) {
            queryParameters.push("uri="+encodeURIComponent(String(uri)));
        }
        if (rdfType !== undefined) {
            queryParameters.push("rdfType="+encodeURIComponent(String(rdfType)));
        }
        if (label !== undefined) {
            queryParameters.push("label="+encodeURIComponent(String(label)));
        }
        if (language !== undefined) {
            queryParameters.push("language="+encodeURIComponent(String(language)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<Infrastructure>>> = this.httpClient.get(`${this.basePath}/infrastructures?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<Infrastructure>>(httpResponse.response));
        }
        return response;
    }
}
