/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs/Observable";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { ProvenanceDTO } from '../model/provenanceDTO';
import { ProvenancePostDTO } from '../model/provenancePostDTO';
import { ResponseFormPOST } from '../model/responseFormPOST';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class ProvenancesService {
    private basePath: string = 'https://localhost';

    constructor(@inject("IApiHttpClient") private httpClient: IHttpClient,
        @inject("IAPIConfiguration") private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }
    /**
     * Get all provenances corresponding to the search params given
     * Retrieve all provenances authorized for the user corresponding to the searched params given
     * @param Authorization Access token given
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     * @param uri Search by provenance uri
     * @param label Search by provenance label
     * @param comment Search by comment
     * @param jsonValueFilter Search by json filter
     
     */
    public getProvenances(Authorization: string, pageSize?: number, page?: number, uri?: string, label?: string, comment?: string, jsonValueFilter?: string, observe?: 'body', headers?: Headers): Observable<Array<ProvenanceDTO>>;
    public getProvenances(Authorization: string, pageSize?: number, page?: number, uri?: string, label?: string, comment?: string, jsonValueFilter?: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<ProvenanceDTO>>>;
    public getProvenances(Authorization: string, pageSize?: number, page?: number, uri?: string, label?: string, comment?: string, jsonValueFilter?: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getProvenances.');
        }

        let queryParameters: string[] = [];
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }
        if (uri !== undefined) {
            queryParameters.push("uri="+encodeURIComponent(String(uri)));
        }
        if (label !== undefined) {
            queryParameters.push("label="+encodeURIComponent(String(label)));
        }
        if (comment !== undefined) {
            queryParameters.push("comment="+encodeURIComponent(String(comment)));
        }
        if (jsonValueFilter !== undefined) {
            queryParameters.push("jsonValueFilter="+encodeURIComponent(String(jsonValueFilter)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<ProvenanceDTO>>> = this.httpClient.get(`${this.basePath}/provenances?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<ProvenanceDTO>>(httpResponse.response));
        }
        return response;
    }
    /**
     * Post provenance(s)
     * Register provenance(s) in the database
     * @param Authorization Access token given
     * @param body JSON format of provenance
     
     */
    public post4(Authorization: string, body?: Array<ProvenancePostDTO>, observe?: 'body', headers?: Headers): Observable<ResponseFormPOST>;
    public post4(Authorization: string, body?: Array<ProvenancePostDTO>, observe?: 'response', headers?: Headers): Observable<HttpResponse<ResponseFormPOST>>;
    public post4(Authorization: string, body?: Array<ProvenancePostDTO>, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling post4.');
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';
        headers['Content-Type'] = 'application/json';

        const response: Observable<HttpResponse<ResponseFormPOST>> = this.httpClient.post(`${this.basePath}/provenances`, body , headers);
        if (observe == 'body') {
               return response.map(httpResponse => <ResponseFormPOST>(httpResponse.response));
        }
        return response;
    }
    /**
     * Update provenance
     * 
     * @param Authorization Access token given
     * @param body JSON format of provenance
     
     */
    public put3(Authorization: string, body?: Array<ProvenanceDTO>, observe?: 'body', headers?: Headers): Observable<ResponseFormPOST>;
    public put3(Authorization: string, body?: Array<ProvenanceDTO>, observe?: 'response', headers?: Headers): Observable<HttpResponse<ResponseFormPOST>>;
    public put3(Authorization: string, body?: Array<ProvenanceDTO>, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling put3.');
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';
        headers['Content-Type'] = 'application/json';

        const response: Observable<HttpResponse<ResponseFormPOST>> = this.httpClient.put(`${this.basePath}/provenances`, body , headers);
        if (observe == 'body') {
               return response.map(httpResponse => <ResponseFormPOST>(httpResponse.response));
        }
        return response;
    }
}
