/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs/Observable";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { SpeciesDTO } from '../model/speciesDTO';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class SpeciesService {
    private basePath: string = 'https://localhost';

    constructor(@inject("IApiHttpClient") private httpClient: IHttpClient,
        @inject("IAPIConfiguration") private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }
    /**
     * Get all species corresponding to the search params given
     * Retrieve all species authorized for the user corresponding to the searched params given
     * @param Authorization Access token given
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     * @param uri Search by species uri
     * @param label Search by species label
     * @param language Select language
     
     */
    public get(Authorization: string, pageSize?: number, page?: number, uri?: string, label?: string, language?: string, observe?: 'body', headers?: Headers): Observable<Array<SpeciesDTO>>;
    public get(Authorization: string, pageSize?: number, page?: number, uri?: string, label?: string, language?: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<SpeciesDTO>>>;
    public get(Authorization: string, pageSize?: number, page?: number, uri?: string, label?: string, language?: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling get.');
        }

        let queryParameters: string[] = [];
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }
        if (uri !== undefined) {
            queryParameters.push("uri="+encodeURIComponent(String(uri)));
        }
        if (label !== undefined) {
            queryParameters.push("label="+encodeURIComponent(String(label)));
        }
        if (language !== undefined) {
            queryParameters.push("language="+encodeURIComponent(String(language)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<SpeciesDTO>>> = this.httpClient.get(`${this.basePath}/species?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<SpeciesDTO>>(httpResponse.response));
        }
        return response;
    }
}
