/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs/Observable";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { ResponseFormPOST } from '../model/responseFormPOST';
import { Unit } from '../model/unit';
import { UnitDTO } from '../model/unitDTO';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class UnitsService {
    private basePath: string = 'https://localhost';

    constructor(@inject("IApiHttpClient") private httpClient: IHttpClient,
        @inject("IAPIConfiguration") private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }
    /**
     * Get a unit
     * Retrieve a unit. Need URL encoded unit URI (Unique resource identifier).
     * @param unit A unit URI (Unique Resource Identifier)
     * @param Authorization Access token given
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     
     */
    public getUnitDetails(unit: string, Authorization: string, pageSize?: number, page?: number, observe?: 'body', headers?: Headers): Observable<Array<Unit>>;
    public getUnitDetails(unit: string, Authorization: string, pageSize?: number, page?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<Unit>>>;
    public getUnitDetails(unit: string, Authorization: string, pageSize?: number, page?: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!unit){
            throw new Error('Required parameter unit was null or undefined when calling getUnitDetails.');
        }

        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getUnitDetails.');
        }

        let queryParameters: string[] = [];
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<Unit>>> = this.httpClient.get(`${this.basePath}/units/${encodeURIComponent(String(unit))}?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<Unit>>(httpResponse.response));
        }
        return response;
    }
    /**
     * Get all units corresponding to the searched params given
     * Retrieve all units authorized for the user corresponding to the user corresponding to the searched params given
     * @param Authorization Access token given
     * @param pageSize Number of elements per page (limited to 150000)
     * @param page Current page number
     * @param uri Search by URI
     * @param label Search by label
     
     */
    public getUnitsBySearch(Authorization: string, pageSize?: number, page?: number, uri?: string, label?: string, observe?: 'body', headers?: Headers): Observable<Array<Unit>>;
    public getUnitsBySearch(Authorization: string, pageSize?: number, page?: number, uri?: string, label?: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<Unit>>>;
    public getUnitsBySearch(Authorization: string, pageSize?: number, page?: number, uri?: string, label?: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling getUnitsBySearch.');
        }

        let queryParameters: string[] = [];
        if (pageSize !== undefined) {
            queryParameters.push("pageSize="+encodeURIComponent(String(pageSize)));
        }
        if (page !== undefined) {
            queryParameters.push("page="+encodeURIComponent(String(page)));
        }
        if (uri !== undefined) {
            queryParameters.push("uri="+encodeURIComponent(String(uri)));
        }
        if (label !== undefined) {
            queryParameters.push("label="+encodeURIComponent(String(label)));
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<Unit>>> = this.httpClient.get(`${this.basePath}/units?${queryParameters.join('&')}`, headers);
        if (observe == 'body') {
               return response.map(httpResponse => <Array<Unit>>(httpResponse.response));
        }
        return response;
    }
    /**
     * Post unit(s)
     * Register new unit(s) in the data base
     * @param body JSON format of unit
     * @param Authorization Access token given
     
     */
    public postUnit(body: Array<UnitDTO>, Authorization: string, observe?: 'body', headers?: Headers): Observable<ResponseFormPOST>;
    public postUnit(body: Array<UnitDTO>, Authorization: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<ResponseFormPOST>>;
    public postUnit(body: Array<UnitDTO>, Authorization: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!body){
            throw new Error('Required parameter body was null or undefined when calling postUnit.');
        }

        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling postUnit.');
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';
        headers['Content-Type'] = 'application/json';

        const response: Observable<HttpResponse<ResponseFormPOST>> = this.httpClient.post(`${this.basePath}/units`, body , headers);
        if (observe == 'body') {
               return response.map(httpResponse => <ResponseFormPOST>(httpResponse.response));
        }
        return response;
    }
    /**
     * Update unit
     * 
     * @param Authorization Access token given
     * @param body JSON format of unit
     
     */
    public putUnit(Authorization: string, body?: Array<UnitDTO>, observe?: 'body', headers?: Headers): Observable<ResponseFormPOST>;
    public putUnit(Authorization: string, body?: Array<UnitDTO>, observe?: 'response', headers?: Headers): Observable<HttpResponse<ResponseFormPOST>>;
    public putUnit(Authorization: string, body?: Array<UnitDTO>, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!Authorization){
            throw new Error('Required parameter Authorization was null or undefined when calling putUnit.');
        }

        if (Authorization) {
            headers['Authorization'] = String(Authorization);
        }

        headers['Accept'] = 'application/json';
        headers['Content-Type'] = 'application/json';

        const response: Observable<HttpResponse<ResponseFormPOST>> = this.httpClient.put(`${this.basePath}/units`, body , headers);
        if (observe == 'body') {
               return response.map(httpResponse => <ResponseFormPOST>(httpResponse.response));
        }
        return response;
    }
}
