/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AgronomicalData { 
    agronomicalObject?: string;
    date?: string;
    value?: string;
    variable?: string;
    sensor?: string;
    incertitude?: string;
}
