/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AnnotationDTO { 
    creator: string;
    motivatedBy: string;
    bodyValues?: Array<string>;
    targets: Array<string>;
    uri?: string;
    creationDate?: string;
}
