/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BrapiVariableTrait { 
    traitDbId?: string;
    traitName?: string;
    brapiclass?: string;
    description?: string;
    synonyms?: Array<string>;
    mainAbbreviation?: string;
    alternativeAbbreviations?: Array<string>;
    entity?: string;
    attribute?: string;
    status?: string;
    xref?: string;
    ontologyReference?: string;
}
