/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BrapiMethod { 
    methodDbId?: string;
    methodName?: string;
    brapiClass?: string;
    description?: string;
    formula?: string;
    ontologyReference?: string;
    reference?: string;
}
