/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BrapiTraitDTO { 
    defaultValue?: string;
    description?: string;
    traitName?: string;
    observationVariables?: Array<string>;
    traitId?: string;
    traitDbId?: string;
}
