/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BrapiObservationSummaryDTO } from './brapiObservationSummaryDTO';


export interface BrapiObservationUnitDTO { 
    blockNumber?: string;
    entryNumber?: string;
    entryType?: string;
    germplasmDbId?: string;
    germplasmName?: string;
    locationDbId?: string;
    locationName?: string;
    observationLevel?: string;
    observationLevels?: string;
    observationUnitDbId?: string;
    observationUnitName?: string;
    observationUnitXref?: string;
    observations?: Array<BrapiObservationSummaryDTO>;
    pedigree?: string;
    plantNumber?: string;
    plotNumber?: string;
    positionCoordinateX?: string;
    positionCoordinateXType?: string;
    positionCoordinateY?: string;
    positionCoordinateYType?: string;
    programDbId?: string;
    programName?: string;
    replicate?: string;
    studyDbId?: string;
    studyName?: string;
    treatments?: Array<string>;
    trialDbId?: string;
    trialName?: string;
}
