/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BrapiObservationDTO { 
    germplasmDbId?: string;
    germplasmName?: string;
    observationDbId?: string;
    observationLevel?: string;
    observationTimeStamp?: string;
    observationUnitDbId?: string;
    observationUnitName?: string;
    observationVariableDbId?: string;
    observationVariableName?: string;
    operator?: string;
    season?: string;
    studyDbId?: string;
    uploadedBy?: string;
    value?: string;
}
