/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BrapiMethod } from './brapiMethod';
import { BrapiScale } from './brapiScale';
import { BrapiVariableTrait } from './brapiVariableTrait';


export interface BrapiVariable { 
    observationVariableDbId?: string;
    observationVariableName?: string;
    ontologyReference?: string;
    synonyms?: Array<string>;
    contextOfUse?: Array<string>;
    growthStage?: string;
    status?: string;
    xref?: string;
    institution?: string;
    scientist?: string;
    submissionTimesTamp?: Date;
    language?: string;
    crop?: string;
    trait?: BrapiVariableTrait;
    method?: BrapiMethod;
    scale?: BrapiScale;
    defaultValue?: string;
    documentationURL?: string;
}
