/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ConcernedItem { 
    uri?: string;
    rdfType?: string;
    labels?: Array<string>;
    objectLinked?: string;
}
