/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ContactBrapi { 
    contactDbId?: string;
    name?: string;
    instituteName?: string;
    email?: string;
    type?: string;
    orcid?: string;
}
