/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgronomicalDataDTO } from './agronomicalDataDTO';
import { ProvenanceDTO } from './provenanceDTO';


export interface DatasetDTO { 
    variableUri?: string;
    provenance?: ProvenanceDTO;
    data?: Array<AgronomicalDataDTO>;
}
