/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Data { 
    uri?: string;
    provenanceUri?: string;
    objectUri?: string;
    variableUri?: string;
    date?: Date;
    value?: any;
}
