/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConcernedItemDTO } from './concernedItemDTO';


export interface DocumentMetadataDTO { 
    uri?: string;
    documentType?: string;
    checksum?: string;
    creator?: string;
    language?: string;
    title?: string;
    creationDate?: string;
    extension?: string;
    comment?: string;
    concernedItems?: Array<ConcernedItemDTO>;
    status?: string;
    serverFilePath?: string;
}
