/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EnvironmentMeasureDTO { 
    sensorUri?: string;
    variableUri?: string;
    date?: string;
    value?: number;
}
