/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConcernedItemWithLabelsDTO } from './concernedItemWithLabelsDTO';
import { PropertyDTO } from './propertyDTO';


export interface EventGetDTO { 
    uri?: string;
    rdfType?: string;
    concernedItems?: Array<ConcernedItemWithLabelsDTO>;
    date?: string;
    properties?: Array<PropertyDTO>;
}
