/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PropertyDTO } from './propertyDTO';


export interface EventPostDTO { 
    rdfType: string;
    concernedItemsUris: Array<string>;
    date: string;
    properties: Array<PropertyDTO>;
    description?: string;
    creator: string;
}
