/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConcernedItemDTO } from './concernedItemDTO';


export interface FileDescriptionDTO { 
    uri?: string;
    rdfType?: string;
    date?: string;
    concernedItems?: Array<ConcernedItemDTO>;
    provenanceUri?: string;
    metadata?: { [key: string]: any; };
}
