/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Group { 
    uri?: string;
    name?: string;
    level?: string;
    description?: string;
    users?: Array<User>;
}
