/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConcernedItemDTO } from './concernedItemDTO';
import { FileInformationDTO } from './fileInformationDTO';
import { ShootingConfigurationDTO } from './shootingConfigurationDTO';


export interface ImageMetadataDTO { 
    rdfType?: string;
    concernedItems?: Array<ConcernedItemDTO>;
    configuration?: ShootingConfigurationDTO;
    fileInfo?: FileInformationDTO;
}
