/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MetadataFileUAVDTO { 
    installation?: string;
    groupPlotType?: string;
    groupPlotAlias?: string;
    groupPlotUri?: string;
    groupPlotSpecies?: string;
    pilot?: string;
    cameraType?: string;
    cameraAlias?: string;
    cameraUri?: string;
    vectorType?: string;
    vectorAlias?: string;
    vectorUri?: string;
    radiometricTargetAlias?: string;
    radiometricTargetUri?: string;
}
