/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { Status } from './status';


export interface Metadata { 
    pagination: Pagination;
    status: Array<Status>;
    datafiles: Array<string>;
}
