/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Pagination { 
    pageSize?: number;
    currentPage?: number;
    totalCount?: number;
    totalPages?: number;
}
