/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProjectPostDTO { 
    name?: string;
    shortname?: string;
    relatedProjects?: Array<string>;
    financialFunding?: string;
    financialReference?: string;
    description?: string;
    startDate?: string;
    endDate?: string;
    keywords?: Array<string>;
    homePage?: string;
    administrativeContacts?: Array<string>;
    coordinators?: Array<string>;
    scientificContacts?: Array<string>;
    objective?: string;
}
