/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Contact } from './contact';
import { FinancialFunding } from './financialFunding';


export interface Project { 
    uri?: string;
    name?: string;
    shortname?: string;
    relatedProjects?: Array<Project>;
    financialFunding?: FinancialFunding;
    financialReference?: string;
    description?: string;
    startDate?: string;
    endDate?: string;
    keywords?: Array<string>;
    homePage?: string;
    administrativeContacts?: Array<Contact>;
    coordinators?: Array<Contact>;
    scientificContacts?: Array<Contact>;
    objective?: string;
}
