/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RdfResourceDTO } from './rdfResourceDTO';


export interface ProjectDTO { 
    uri?: string;
    name?: string;
    shortname?: string;
    financialFunding?: RdfResourceDTO;
    financialReference?: string;
    description?: string;
    startDate?: string;
    endDate?: string;
    homePage?: string;
    objective?: string;
}
