/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContactDTO } from './contactDTO';
import { RdfResourceDTO } from './rdfResourceDTO';


export interface ProjectDetailDTO { 
    uri?: string;
    name?: string;
    shortname?: string;
    relatedProjects?: Array<RdfResourceDTO>;
    financialFunding?: RdfResourceDTO;
    financialReference?: string;
    description?: string;
    startDate?: string;
    endDate?: string;
    keywords?: Array<string>;
    homePage?: string;
    administrativeContacts?: Array<ContactDTO>;
    coordinators?: Array<ContactDTO>;
    scientificContacts?: Array<ContactDTO>;
    objective?: string;
}
