/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Property { 
    rdfType?: string;
    rdfTypeLabels?: Array<string>;
    relation?: string;
    relationLabels?: Array<string>;
    value?: string;
    valueLabels?: Array<string>;
    domain?: string;
    labels?: { [key: string]: string; };
}
