/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PropertyPostDTO } from './propertyPostDTO';


export interface ScientificObjectPostDTO { 
    rdfType?: string;
    geometry?: string;
    experiment?: string;
    isPartOf?: string;
    year?: string;
    properties?: Array<PropertyPostDTO>;
}
