/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PropertyDTO } from './propertyDTO';


export interface ScientificObjectDTO { 
    uri?: string;
    rdfType?: string;
    geometry?: string;
    experiment?: string;
    isPartOf?: string;
    label?: string;
    properties?: Array<PropertyDTO>;
    uriExperiment?: string;
}
