/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface StudySearchDTO { 
    commonCropName?: string;
    seasonDbId?: string;
    studyDbIds?: Array<string>;
    studyNames?: Array<string>;
    sortBy?: string;
    sortOrder?: string;
    page?: number;
    pageSize?: number;
}
