/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdditionalInfo } from './additionalInfo';


export interface StudyDTO { 
    active?: string;
    additionalInfo?: AdditionalInfo;
    commonCropName?: string;
    documentationURL?: string;
    endDate?: string;
    locationDbId?: string;
    locationName?: string;
    name?: string;
    programDbId?: string;
    programName?: string;
    seasons?: Array<any>;
    startDate?: string;
    studyDbId?: string;
    studyName?: string;
    studyType?: string;
    studyTypeDbId?: string;
    studyTypeName?: string;
    trialDbId?: string;
    trialName?: string;
}
