/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TripletDTO { 
    s?: string;
    p?: string;
    o?: string;
    o_type?: string;
    o_lang?: string;
    g?: string;
}
