/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Uri { 
    uri?: string;
    rdfType?: string;
    label?: string;
    properties?: { [key: string]: string; };
    annotations?: { [key: string]: string; };
}
