/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserDTO { 
    email?: string;
    password?: string;
    firstName?: string;
    familyName?: string;
    address?: string;
    phone?: string;
    affiliation?: string;
    orcid?: string;
    admin?: string;
    groupsUris?: Array<string>;
}
