/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface VectorDTO { 
    uri?: string;
    rdfType?: string;
    label?: string;
    brand?: string;
    serialNumber?: string;
    inServiceDate?: string;
    dateOfPurchase?: string;
    personInCharge?: string;
}
